### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by glibersat** [pyofwave/PyOfWave#10]
The README states it's covered under MPL2rc1 and pyofwave/__ init__.py has an Apache license. If I'm correct, it is under MPL2rc1 and we should :
- upgrade to MPL2rc2 ;
- Remove the Apache header from this init file.

Is that right ?

**Comment by alcinnz** [comment]
That's right. That Apache license must be left from PyGoWave.

**Comment by alcinnz** [comment]
Thanks for spotting that.
