### ISSUE TITLE
About Event Registy

### ISSUE THREAD

**Issue by atiberghien** [pyofwave/PyOfWave#17]
Hi

as you said in a previous message :

> Unlike Google and Apache, I have decided it's advantageous to leverage XMPP to create ONE protocol between servers (Federation), web clients (via BOSH), and robots/native clients. This drastically cuts down the amount of work that needs doing (especially with your help, thanks) as XMPP does a lot of the work already and work doesn't need to be duplicated (and no low level networking).
> 
> Anyways, these different clients (servers, web, and native, particularly servers) have different requirements for what their sent. The event registry is a simple way to handle any complexity there

If I understand correctly, the EventRegistry is not dedicated to only deal with event related to operations, is it ?

**Comment by alcinnz** [comment]
Yes, other events can go through the events registry, and some operations would be useless as events (the getters). The main example of none operation events would be /docs/protocols/Wave Protocol DTDs/blip.dtd, although any data returned from operations would send updates as events (mainly wave.dtd).

However, I try to keep events the same as operations as then in Federation, POW could register the operations as events and handle them as requests.
