### ISSUE TITLE
Missing files and imports

### ISSUE THREAD

**Issue by glibersat** [pyofwave/PyOfWave#2]
Hi,

I've found two problems with the current state:
- PREFERENCES.PY is complaining against a missing auth.bogus (It can be easily faked by writing a two lines file) ;
- Operation.py imports "opdev" which I can't find anywhere. This one is a blocker for now.

Thx,

Guillaume

**Comment by alcinnz** [comment]
Try running it again, I might have fixed it. Different problem now, which I'm having difficulty spotting. 

When running it (with tests imported), the test operation call can't access any global values of the module. According to output of debug prints I left in the file, all globals I defined equals `None`. Maybe you can help me spot it.

**Comment by alcinnz** [comment]
A possible fix would be to change the use of runpy to `__import__`. 

Oh, and I removed auth.bogus so Python XMPP Server could provide it for us. I've got these changes planned in /docs/server/Extending/.

**Comment by glibersat** [comment]
I can spot two problems with the current implementation:
1. the plugin system is odd and not using standard python entry points (which is never good when a "standard" exists and has been proof tested) ;
2. The tests belongs to the packages, we should setup a real test suite to prevent packages from being imported wildly.

I can handle these problems while you go on with the operation implementation, then we'll merge back my changes so that we have a cleaner code design and a working operation implementation. What do you think ?

Btw, I've read the whole code, it's pretty clear (good point :) ) and the effort of string documentation and the few docs around are very helpful, thanks for having taken time writing them!

PS: We may use git-flow if you're ok, it is very handy when working on different features at the same time.

**Comment by alcinnz** [comment]
Are you talking about decorators? Since operators are the plugins I might try that today. 

As for a test suite, I have one setup for the client (jasmine)  and it'd be nice to have one for the server. Go ahead. 

Thank you, as for git-flow, I'll work on learning it and may use it sometime, but I think it's a bit much for now.

**Comment by alcinnz** [comment]
Works now it uses decorators.

**Comment by glibersat** [comment]
I didn't have decorators in mind, but I'll dig into the code today to see the changes ! :-)

**Comment by alcinnz** [comment]
Well it works very nicely.

**Comment by glibersat** [comment]
Indeed, that's quite nice :)
That's only one part of the puzzle tho. People wanting to add new operations still have to write them INSIDE the package, which is not good. My former idea was to add a plugin system, so that you can write new operations _outside_ pyofwave: that's much better for maintainability. But I think this is low priority for now.

**Comment by alcinnz** [comment]
Look at the test case. They can be outside as long as they're ran.

**Comment by glibersat** [comment]
Ok, I think I now understand how you want to handle them :-)
I'll include a mechanism in the config file to allow one to load an external operation.

Thanks for the clarification (and thanks for the merge!)

**Comment by alcinnz** [comment]
O.K., cool. That'll be a useful addition for people who don't want to dig into the code. 

You're welcome.
