### ISSUE TITLE
performOperation bad number of params

### ISSUE THREAD

**Issue by atiberghien** [pyofwave/PyOfWave#4]
Hi,

(i'm working on pyofwave  with Guillaume aka glibersat)

There is actually a problem with the performOperatiofunction in pyofwave_server/pyofwave/core/operation.py. The declared function takes 2 params, events and tag, whereas it function is called with 3 params in protocols/client/client.py and core/tests/test_operation.py.

What is the good one : 2 or 3 parameters ?

Thx
Alban

**Comment by alcinnz** [comment]
I'm looking into this. I'll get back to you soon.

**Comment by alcinnz** [comment]
It's legacy in the docs when I was planning to use Google's old Federation and Simple Data protocols. 

I'll fix it in the docs.

**Comment by alcinnz** [comment]
Thanks for spotting this.
