### ISSUE TITLE
Alpha/Beta observers: Mismatch between code and doc?

### ISSUE THREAD

**Issue by glibersat** [pyofwave/PyOfWave#6]
Hi,

In the code, I can read:
alphaDeltaObservable = DeltaObservable() #for operations in permanent memory
betaDeltaObservable = DeltaObservable()  #for operations before they arrive at permanent memory

and the doc reads:
Also ensure that the applyDelta method is set to observe betaDeltaObservable, betaDeltaObservable.addObserver(STORAGE_OBJECT.applyDelta).

So, if "permanent memory" is a backing store, which one is correct ? Are beta observers tied to the backing store and alpha one to the volatile memory ?

Thx!

**Comment by alcinnz** [comment]
All `DeltaObservable`s are a simple multithreaded observer system. The difference I had on mind was that `betaDeltaObservable` transports deltas to the `STORAGE_OBJECT` while alpha transports them from it. This allows the datastorage to not apply it if there's an error in it.

**Comment by glibersat** [comment]
Ok, so to make sure I understand, beta observers acting as "transaction buffers" (before really applying the deltas) while the alpha ones send modification to the outside world? Sorry for asking again, but I really want to make sure I get that! Thx.

**Comment by alcinnz** [comment]
Yes, that's right.
