### ISSUE TITLE
tests command not working

### ISSUE THREAD

**Issue by alcinnz** [pyofwave/PyOfWave#7]
I tried using the setup.py script to run the tests command but it complains:

`/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_require'`

I've been running the tests directly.

---

Also, when I access pyofwave.core.delta, it complains that an environment variable isn't set.  It'd be convenient if it set it to global_settings.py by default.

**Comment by glibersat** [comment]
About the tests, this pull request fixes it the right way.

About accessing the core package, it calls the configuration mechanism since there's a reference to "settings.XXX" at the module level. I don't want that to be silent since the user should be aware that he _needs_ to setup a proper configuration before using pyofwave. Making it silent would just make the user _think_ it's properly configured, while it isn't.

So, if you run your experiments from "bin/pyofwave", that shoudn't be a problem and if you want to try things from a shell, then exports PYOFWAVE_SETTINGS_MODULE or user setup_environ from "pyofwave.conf". There's an example inside "pyofwave/__ init__.py".

**Comment by alcinnz** [comment]
O. K. cool. Just, how about putting this in the for Wave Providers alongside available settings? If I didn't know how to use the settings, they definitely won't.

**Comment by alcinnz** [comment]
Still having problems. The tests command reports:

   `twisted/runner/portmap.c:10:20: fatal error: Python.h: No such file or directory`

Ubuntu Oneiric, if this is issue OS dependent.

I want to figure this out so that I can access the `delta` module while debugging to get the operations working with them. 

## 

I put what I understand on using setup-tools and configuration in the For Wave Providers section.

**Comment by glibersat** [comment]
Hi, thanks for testing. I'll investigate this in the afternoon (in 6hours, I'm GMT+1) and also finish updating the doc for the Wave Providers.
If you could do a "pip freeze" in your env, that could help me narrow down the problem.
I'll also make sure you can access the delta module, but If I'm correct there's a direct reference to settings.SOMETHING at the module level. How are you running your experiments and debugging ?

**Comment by alcinnz** [comment]
pip freeze (once installed) outputs:

   Warning: cannot find svn location for distribute==0.6.16dev-r0
    Brlapi==0.5.5
   BzrTools==2.4.0
   GnuPGInterface==0.3.2
   Mako==0.4.1
   MarkupSafe==0.12
   PAM==0.4.2
   PIL==1.1.7
   PyOfWave==0.1
   Twisted-Core==11.0.0
   Twisted-Names==11.0.0
   Twisted-Web==11.0.0
   adium-theme-ubuntu==0.3.1
   apt-xapian-index==0.44
   apturl==0.5.1ubuntu1
   argparse==1.1
   bzr==2.4.1
   chardet==2.0.1
   command-not-found==0.2.44
   configglue==1.0
   configobj==4.7.2
   defer==1.0.2
   ## FIXME: could not find svn URL in dependency_links for this package:
   distribute==0.6.16dev-r0
   duplicity==0.6.15
   gnome-app-install==0.4.7-nmu1ubuntu2
   httplib2==0.7.1
   jockey==0.9.4
   keyring==0.6.2
   launchpadlib==1.9.8
   lazr.restfulclient==0.11.2
   lazr.uri==1.0.2
   louis==2.3.0
   lxml==2.3
   nvidia-common==0.0.0
   oauth==1.0.1
   onboard==0.96.1
   oneconf==0.2.6.7
   papyon==0.5.5
   paramiko==1.7.7.1
   pexpect==2.3
   piston-mini-client==0.6
   protobuf==2.4.0a
   pyOpenSSL==0.12
   pycrypto==2.3
   pycups==1.9.59
   pycurl==7.19.0
   pyinotify==0.9.1
   pyserial==2.5
   pysmbc==1.0.10
   python-apt==0.8.0ubuntu9
   python-dateutil==1.4.1
   python-debian==0.1.20ubuntu2
   python-virtkey==0.60.0
   pyxdg==0.19
   rdflib==2.4.2
   sessioninstaller==0.0.0
   simplejson==2.1.6
   system-service==0.1.6
   ubuntu-sso-client==1.4.0
   ubuntuone-couch==0.3.0
   ubuntuone-installer==2.0.0
   ubuntuone-storage-protocol==2.0.0
   ufw==0.30.1-2ubuntu1
   unattended-upgrades==0.1
   usb-creator==0.2.23
   wadllib==1.2.0
   wsgi-intercept==0.4
   wsgiref==0.1.2
   xdiagnose==1.1
   xkit==0.0.0
   zope.interface==3.6.1

## 

And if you haven't seen it already, `delta` does directly access settings to create a process pool using those preferences. 

Before now, I ran the test script directly.

**Comment by alcinnz** [comment]
Still not working, but I think I can fix it with http://alexsleat.co.uk/2011/01/01/fatal-error-python-h-no-such-file-or-directory/ .

Slight adjustment and it works now.

**Comment by alcinnz** [comment]
Nothing PyOfWave specific, just platform issues.
